name: auto_upload
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: auto_upload
        run: |
          # sudo apt-get update && sudo apt-get install -y python3
          python3 -m pip install --user yt-dlp
          ls -a
          python3 auto_uploader.py
