name: auto_upload
on:
  schedule:
    - cron: '00 08 * * 2'  # runs at 08:00 UTC every Tuesday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v2

      - name: setup
        run: |
          sudo apt-get update && sudo apt-get install -y python3-selenium ffmpeg
          python3 -m pip install --user yt-dlp

      - name: auto upload
        env:
          EMAIL: ${{ secrets.EMAIL }} 
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python3 auto_uploader.py
